name: publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: tests/IntegrationConsumer/global.json

      - name: Pack SDK
        shell: bash
        run: |
          version="${GITHUB_REF_NAME#v}"
          dotnet pack ./src/Atya.Build.Sdk.csproj -c Release -o ./artifacts -p:PackageVersion="$version"

      - name: Log in to NuGet.org
        id: login
        uses: NuGet/login@v1
        with:
          user: ArsenAsulyan

      - name: Push package
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json

      - name: Attest package provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ./artifacts/*.nupkg
